# Generated by Django 4.2.4 on 2023-12-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='leaves_remaining',
            field=models.FloatField(default=0.0),
        ),
    ]
