# Generated by Django 4.2.4 on 2023-09-30 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_user_leader_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='leader_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
