# Generated by Django 4.2.4 on 2023-10-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leaves_remaining',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
