# Generated by Django 4.2.4 on 2023-10-28 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(null=True)),
                ('logout_time', models.DateTimeField(null=True)),
                ('is_present', models.BooleanField(default=False, null=True)),
                ('leave_details', models.TextField(null=True)),
                ('work_hours', models.TextField(null=True)),
                ('created_at', models.DateField(null=True)),
                ('week_day', models.TextField(null=True)),
                ('remarks', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRegularization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_id', models.UUIDField()),
                ('date', models.DateField(null=True)),
                ('login_time', models.DateTimeField(null=True)),
                ('logout_time', models.DateTimeField(null=True)),
                ('working_hours', models.TextField(null=True)),
                ('reason', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('shift', models.TextField()),
                ('event_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Leaveapprovals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.TextField(default='')),
                ('leave_reason', models.TextField(default='')),
                ('leave_details', models.JSONField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserBasicDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emp_no', models.CharField()),
                ('emp_name', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email_id', models.EmailField(max_length=254)),
                ('father_name', models.TextField(null=True)),
                ('name_as_aadhar', models.TextField()),
                ('emergency_contact_name', models.TextField(null=True)),
                ('emergency_contact', models.TextField()),
                ('aadhar_number', models.TextField()),
                ('mobile_number', models.TextField()),
                ('designation', models.TextField()),
                ('location', models.TextField()),
                ('department', models.TextField(null=True)),
                ('permanent_address', models.TextField(null=True)),
                ('temporary_address', models.TextField(null=True)),
                ('date_of_joining', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField()),
                ('pan', models.TextField(null=True)),
                ('maritial_status', models.TextField(null=True)),
                ('ctc', models.CharField(null=True)),
                ('is_pf_eligible', models.BooleanField(null=True)),
                ('is_esi_eligible', models.BooleanField(null=True)),
                ('is_night_shift', models.BooleanField(default=False)),
            ],
        ),
    ]
