# Generated by Django 4.2.4 on 2023-09-16 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corehr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBasicDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emp_no', models.CharField()),
                ('emp_name', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email_id', models.EmailField(max_length=254)),
                ('father_name', models.TextField(null=True)),
                ('name_as_aadhar', models.TextField()),
                ('emergency_contact_name', models.TextField(null=True)),
                ('emergency_contact', models.TextField()),
                ('aadhar_number', models.IntegerField()),
                ('mobile_number', models.TextField()),
                ('designation', models.TextField()),
                ('location', models.TextField()),
                ('department', models.TextField(null=True)),
                ('permanent_address', models.TextField(null=True)),
                ('temporary_address', models.TextField(null=True)),
                ('date_of_joining', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField()),
                ('pan', models.TextField(null=True)),
                ('maritial_status', models.TextField(null=True)),
                ('ctc', models.IntegerField(null=True)),
                ('is_pf_eligible', models.BooleanField(null=True)),
                ('is_esi_eligible', models.BooleanField(null=True)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='attendancelogs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
