# Generated by Django 4.2.4 on 2023-09-02 08:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corehr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(null=True)),
                ('logout_time', models.DateTimeField(null=True)),
                ('is_present', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corehr.user')),
            ],
        ),
    ]
