# Generated by Django 4.2.4 on 2023-09-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corehr', '0002_attendancelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelogs',
            name='work_hours',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_night_shift',
            field=models.BooleanField(default=False),
        ),
    ]
