# Generated by Django 4.2.4 on 2023-11-04 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corehr', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resignation_date', models.DateField()),
                ('personal_phone_no', models.TextField()),
                ('personal_mail_id', models.TextField()),
                ('resignation_reason', models.TextField()),
                ('status', models.TextField(null=True)),
                ('date_of_exit', models.DateField(null=True)),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resg_applied_by', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resg_approver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
