# Generated by Django 4.2.4 on 2023-09-23 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corehr', '0002_userbasicdetails_alter_attendancelogs_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('shift', models.TextField()),
                ('event_type', models.TextField()),
            ],
        ),
    ]
