# Generated by Django 4.2.4 on 2023-09-30 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corehr', '0003_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaveapprovals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_details', models.JSONField()),
                ('status', models.TextField()),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_by', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
