# Generated by Django 4.2.4 on 2023-11-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corehr', '0003_resignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicdetails',
            name='blood_group',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userbasicdetails',
            name='project_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userbasicdetails',
            name='role',
            field=models.TextField(null=True),
        ),
    ]
