# Generated by Django 4.2.4 on 2023-09-07 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corehr', '0003_attendancelogs_work_hours_user_is_night_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelogs',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time of Creation'),
            preserve_default=False,
        ),
    ]
