# Generated by Django 4.2.4 on 2023-12-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corehr', '0004_userbasicdetails_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapprovals',
            name='leave_count',
            field=models.FloatField(default=0),
        ),
    ]
