# Generated by Django 4.2.4 on 2023-09-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corehr', '0004_leaveapprovals'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapprovals',
            name='leave_reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='leaveapprovals',
            name='leave_type',
            field=models.TextField(default=''),
        ),
    ]
