# Generated by Django 4.2.4 on 2023-09-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corehr', '0005_alter_attendancelogs_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelogs',
            name='week_day',
            field=models.TextField(null=True),
        ),
    ]
