# Generated by Django 4.2.4 on 2023-10-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corehr', '0005_leaveapprovals_leave_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelogs',
            name='leave_details',
            field=models.TextField(null=True),
        ),
    ]
