# Generated by Django 4.2.4 on 2023-10-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corehr', '0006_attendancelogs_leave_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelogs',
            name='remarks',
            field=models.TextField(default='', null=True),
        ),
    ]
