# Generated by Django 4.2.4 on 2024-01-26 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corehr', '0006_usertimelogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceAmount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advance_date', models.DateField()),
                ('personal_phone_no', models.TextField()),
                ('personal_mail_id', models.TextField()),
                ('advance_reason', models.TextField()),
                ('status', models.TextField(null=True)),
                ('cleared_date', models.DateField(null=True)),
                ('advance', models.FloatField(default=0.0)),
                ('pending', models.FloatField(default=0.0)),
                ('collected', models.FloatField(default=0.0)),
                ('instalments', models.FloatField(default=0.0)),
                ('permanent_address', models.TextField()),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adv_applied_by', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adv_approver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collected_date', models.TextField()),
                ('collected_amount', models.FloatField(default=0.0)),
                ('advance_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advance_rec', to='corehr.advanceamount')),
            ],
        ),
    ]
