# Generated by Django 4.2.4 on 2023-10-14 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corehr', '0007_attendancelogs_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRegularization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_id', models.UUIDField()),
                ('date', models.DateField(null=True)),
                ('login_time', models.DateTimeField(null=True)),
                ('logout_time', models.DateTimeField(null=True)),
                ('working_hours', models.TextField(null=True)),
                ('reason', models.TextField()),
                ('status', models.TextField()),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_applied_by', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_approver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
